name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Test
          run: ./gradlew test
        - name: Jar with Gradle
          run: ./gradlew assemble
        - name: Docker Hub Build And Push
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run:
          docker run --network container:this-box-server-api appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/